# These are supported funding model platforms

github: [Sh031224] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: Sh031224 # Replace with a single Open Collective username
