name-template: "v$RESOLVED_VERSION ðŸŒˆ"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
categories:
  - title: "ðŸš€ Features"
    label: "enhancement"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "bug"
template: |
  ## Changes

  $CHANGES
