name: Bug Report
description: Create a bug report
labels: "bug"
body:
  - type: markdown
    attributes:
      value: Please fill out this form as completely as possible.
  - type: input
    attributes:
      label: What browser are you using? (if relevant)
      description: "Please specify the exact version. For example: Chrome 100.0.4878.0"
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
