on:
  push:
    branches:
      - main
      - v2
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Create .env file
        run: |
          jq -r 'keys[] as $k | "export \($k)=\(.[$k])"' <<< "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: pnpm run test:report

      - name: Upload codecov server
        uses: codecov/codecov-action@v3
        with:
          root_dir: ./apps/server
          flags: server
      - name: Upload codecov web
        uses: codecov/codecov-action@v3
        with:
          root_dir: ./apps/web
          flags: web
